import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientNav from "../components/ClientNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="bg-gray-800 p-4 text-white">
          <ClientNav />
        </header>
        <main>{children}</main>
        <footer className="bg-gray-800 text-white text-center p-4 mt-4">
          <p>&copy; 2023 Your Name. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
